### ISSUE TITLE
chebyshev basis

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/PolyJuMP.jl#17]
I have read that using a chebyshev basis can improve the numerical performance of various relevant algorithms and I would like to test that.

Perhaps this question is more appropriate in MultivariatePolynomials.jl, but I want to use PolyJuMP directly it so I'll ask here. How would we go about adding this new basis type to the current architecture? We need functions like differentiation, evaluation etc to work with the chebyshev basis, and we need the polyconstraints to know what basis they are working over, etc. 

It seems that @rdeits was playing with the chebyshev basis in [Mayday.jl](https://github.com/rdeits/Mayday.jl/blob/master/src/basis.jl#L50) - but the design of that package was quite different to this one.

@blegat @joehuchette 

Here is some (pseudo)code to generate a chebyshev basis vector:
```julia
@polyvar(t)
cheb_basis = Vector{??}(r+1)
cheb_basis[r+1] = 1
cheb_basis[r] = t
for k in r-1:-1:1
    cheb_basis[k] = 2*t*cheb_basis[k+1] - cheb_basis[k+2]
end
```

**Comment by blegat** [comment]
What do you mean by differentiation should work with the chebyshev basis ? We should be able to say differentiate p with respect to an element of the basis instead of a variable ? When is this useful ? Note that even with the monomial, basis, we cannot differentiate by the elements of the basis (i.e. the monomials) but only by the variables. However, you can ask for the coefficient of a monomial (which is kind of the replacement).

**Comment by chriscoey** [comment]
I don't mean anything special by it, just that should still be able to differentiate with respect to the polyvar(s). So with one polyvar `t` and degree 2 you have the basis `[2t^2-1, t, 1]` and differentiating the polynomial `c[1](2t^2-1) + c[2]t + c[3]` wrt `t` should give `4c[1]t + c[2]`. Maybe that's trivial to implement, not sure.

The important part is: I'm looking for similar functionality to what it seems @rdeits was implementing in Mayday.jl with the Chebyshev basis of the first kind. So for example, the following code (modified from his example spotopt_van_der_pol.jl) works for me:
```
using JuMP
using Mayday
using Base.Test
using Mosek

basis_generator = Mayday.chebyshev_polynomial_first_kind
x, y = generators(:x, :y)

# System dynamics:
f = -[y; (1 - x^2) * y - x]

# Construct a Lyapunov function
J = jacobian(f, :x, :y)
A = evaluate(J, 0.0, 0.0)
P = lyap(A', eye(2,2))
V = Mayday.quad([x; y], P)
Vdot = sum(grad(V, :x, :y) .* f)

# Solve for the maximum RoA, parameterized by rho
model = Model(solver=MosekSolver())
@variable(model, rho)
lambda = defPolynomial(model, [:x, :y], 4, basis_generator)
d = Int(floor(deg(lambda * Vdot) / 2 - 1))
addSoSConstraint(model, lambda * Vdot + (V - rho) * (x^2 + y^2)^d, basis_generator)
@objective(model, Max, rho)
solve(model)

result = getvalue(rho)
@show result

# Verify rho against the answer we get from spotless
@test abs(result - 2.3045) < 1e-3
```
I get similar (but slightly different) answers whether or not `basis_generator` is set to `Mayday.monomial` or to `Mayday.chebyshev_polynomial_first_kind`

**Comment by joehuchette** [comment]
@chriscoey I'm confused about differentiation: isn't that currently what happens?

```jl
using MultivariatePolynomials, DynamicPolynomials, JuMP, PolyJuMP
@polyvar(t)
m = Model()
@variable(m, c[1:3])
p = c[1]*(2t^2-1) + c[2]*t + c[3]
differentiate(p, t) # => (4 c[1])t + (c[2])
```
or
```jl
module FooBar
    import JuMP, PolyJuMP, MultivariatePolynomials

    function createpoly(m::JuMP.Model, p::Union{PolyJuMP.Poly{false, :Default}, PolyJuMP.Poly{false, :Classic}}, category::Symbol)
        MultivariatePolynomials.polynomial([JuMP.Variable(m, -Inf, Inf, category)*p.x[i] for i in 1:length(p.x)])
    end
end

using MultivariatePolynomials, DynamicPolynomials, JuMP, PolyJuMP
@polyvar(t)
Z = [2t^2-1, t, 1]
m = Model()
setpolymodule!(m, FooBar)
@variable(m, p, Poly(Z))
differentiate(p, t) # => (4 col_1)t + (col_2)
```
What is it about that snippet of code from MayDay that isn't currently available in PolyJuMP and friends?

**Comment by chriscoey** [comment]
Perhaps the differentiation is not an issue then. What I'd like is for there to be modeling support to automatically handle a chebyshev basis, rather than make the user construct it manually.

**Comment by chriscoey** [comment]
I don't feel that I have a strong enough grasp of the design/architecture of PolyJuMP and Multivariate Polynomials and DynamicPolynomials to go and try to make a PR without discussing it with y'all

**Comment by joehuchette** [comment]
Would it suffice to have a
```jl
Z = chebyshevpoly(t, degree)
```
function?

**Comment by chriscoey** [comment]
I'm not entirely sure actually - something made me think that's not enough. But there's only one way to find out... let me try it and get back to you.

**Comment by chriscoey** [comment]
I can't figure it out. Here's where I started:
```
Z = Vector{DynamicPolynomials.Monomial{true}}(r+1)
Z[r+1] = 1 
Z[r] = t
for k in r-1:-1:1
    Z[k] = 2*t*Z[k+1] - Z[k+2]
end
```
I'm getting MethodErrors after line 1

**Comment by chriscoey** [comment]
had the type wrong
```
Z = Vector{DynamicPolynomials.Polynomial{true,Int64}}(r+1)
Z[r+1] = 1 + 0t
Z[r] = t
for k in r-1:-1:1
    Z[k] = 2*t*Z[k+1] - Z[k+2]
end
```
gives me something now

**Comment by joehuchette** [comment]
```jl
function cheb(t,r)
    r == 0 && return 0t+1
    r == 1 && return 1t+0
    return 2*t*cheb(t,r-1) - cheb(t,r-2)
end

chebyshevbasis(t, degree) = [cheb(t,i) for i in 0:degree]

```

**Comment by chriscoey** [comment]
OK seems to work. I guess I was getting confused by all the types. So if a multivariate version of that can be added, it would be a useful tool. 

@rdeits did you notice a difference computationally when you used the chebyshev basis?

**Comment by blegat** [comment]
There is four cases to consider (the first two are independent to the SOS cone):
1) Creation of a *free* polynomial `p`. Currently, the user needs to do `@variable m p Poly(X)` where `X` is a vector of monomials obtained, e.g. with `monomials(x, 2:3)`.
2) Constraining a polynomial `p` to be zero. Currently, we set each coefficient to be zero.
3) Creation of a SOS polynomial `p`. Currently, the user needs to do `@variable m p SOSPoly(X)` where `X` is obtained, e.g. with `monomials(x, 2:3)` (note that `p` is `X^T Q X` so the monomials of `p` are not really `X`).
4) Constraining a polynomial `p` to be SOS. We need to find the right `X` (e.g. using the newton polytope) and create an SOS polynomial `q` using 3. Then we constraint `p - q` to be zero using 2.

They can be generalized to any polynomial basis as follows:
1) Given a basis `b`, we could set `p = sum a_i b_i`.
2) Constraining a polynomial `p` to be zero. We need `N` hyperplanes such that their intersection is the origin. Then we ask `p` to belong to each hyperplane. The hyperplane can be seen as measures. The canonical choice is to take a measure `μ` per polynomial in the basis `b` such that `<μ, b> = 1` and `<μ, b'> = 0` for each other polynomial `b'` in the basis. For the monomial basis, it `<μ, p>` is the coefficient of the monomial considered. Note that for the Lagrangian basis, `μ` for `b_i` (being the polynomial equal to `1` at `x_i` and `0` otherwise) is the dirac at `x_i` so that `<μ, p> = p(x_i)`.
3) `X` will be a vector of polynomials of the basis `b`.
4) Typically, we take an outer estimate of the newton polytope by looking only at the range of degrees. For instance if `p` has monomials up to degree `2d`, we will take the basis up to degree `d`.

I suggest the following interface for polynomial basis
```julia
abstract type AbstractPolynomialBasis end
"""
    setnewtonpolytope!(B::AbstractPolynomialBasis, p)

The basis should be the vector `X` needed for `p = X^T Q X` to be possible.
"""
"""
    defaultdualbasis(B::AbstractPolynomialBasis)

Returns the measure basis `μ` such that with one `μ` for each `b` in the basis such that `<μ, b> = 1` and `<μ, b'> = 0` for each other polynomial `b'` in the basis
"""
abstract type AbstractMeasureBasis end
```

The basis will implement `Base.start`, `Base.next`, ... so that the element of the basis can be obtained. `setnewtonpolytope!` will be used by 4. to know which `X` to give to 3 and `defaultdualbasis` will be used by 4. to know which dual basis to give to 2.

There will be special basis `FixedPolynomialBasis` to be used in 1. with `@variable` and `FixedGramBasis` to be used in 3. with `@variable`.

What do you think ?

**Comment by joehuchette** [comment]
I think the source of the confusion is that we only want to do polynomial optimization (nothing to do with sum of squares), and the PolyJuMP modeling layer is still a bit too intertwined with SumOfSquares. I think there should be a default polymodule that just adds polynomial variables and constraints without any of the fancy transformations that you need to do with SOS. It's essentially what I've implemented on my own (and it's about 10 lines), but there isn't any reason that it shouldn't live in PolyJuMP.

**Comment by blegat** [comment]
I would be ok to move the part of SumOfSquares that does 1. and 2. to PolyJuMP. We could change the design of PolyJuMP a bit for that: Instead of having a default polymodule, we have a default cone approximating the cone of nonnegative polynomials. For 3. and 4., PolyJuMP transform the cone to the default cone and it gets to SumOfSquares.jl (or one other) using multiple dispatch.

**Comment by chriscoey** [comment]
Thanks Benoit for putting so much thought into this. I'm sorry to be kind
of demanding - I am willing to help implementation, but will need guidance.

Echoing Joey, I think polyjump should be about modeling with nonnegative
polynomials, and sumofsquares should be about taking those models and
automatically approximating them with specifically SOS models. The reason I
would like a clear distinction there is that SOS is not the only way to
solve polynomial nonnegativity problems, at least if you don't care about
NP-hardness. As a MIPper, I have no qualms about trying to attack NP-hard
problems directly, without approximation (even if it means I can't publish
in the same journals lol). Ideally I think when someone is modeling their
problem naturally with nonneg polys, they should not have to think about
SOS, except when they set the polymodule to SumOfSquares (rather than a
potential alternative). So yeah, nothing in PolyJuMP should be SOS-specific.

If you know of applications where someone specifically wants
SOS-polynomials rather than (the larger set of) nonneg-polynomials
(possibly on a domain), then there could be a way in polyjump to specify
that p is SOS rather than just p is nonneg. I'm not sure how often that
comes up naturally in applied problems though.

> --
Chris

**Comment by chriscoey** [comment]
In your last post you recommended a "default cone approximating the cone of nonnegative polynomials". I'm saying that there should be no approximation and no transformation going on in PolyJuMP. That means that, for the near future, a PolyJuMP model can't be understood by MOI, which is fine. It has go through a polymodule before it can go to a solver. The polymodule should perform all transformations, including dealing with the semialgebraic set domains etc. So PolyJuMP is just a convenient modeling feature. 

Joey and I may make an alternative polymodule down the track, one that handles the nonneg-on-set poly-given-some-basis constraints.

**Comment by blegat** [comment]
> Echoing Joey, I think polyjump should be about modeling with nonnegative
polynomials, and sumofsquares should be about taking those models and
automatically approximating them with specifically SOS models. (...) nothing in PolyJuMP should be SOS-specific.

It is already the case no ? Nothing in PolyJuMP is SOS-specific

> Joey and I may make an alternative polymodule down the track, one that handles the nonneg-on-set poly-given-some-basis constraints.

This is the reason I suggest to rethink PolyJuMP to share the cases that are not specific to the cone of nonnegative polynomials. This is even more true if we add polynomial basis, there will be more to share.

> In your last post you recommended a "default cone approximating the cone of nonnegative polynomials". I'm saying that there should be no approximation and no transformation going on in PolyJuMP. That means that, for the near future, a PolyJuMP model can't be understood by MOI, which is fine. It has go through a polymodule before it can go to a solver. The polymodule should perform all transformations, including dealing with the semialgebraic set domains etc. So PolyJuMP is just a convenient modeling feature.

It does not have to be an approximation it is just a cone for dispatching to the right submodule. It is a different way to dispatch than polymodule.

**Comment by chriscoey** [comment]
OK so looks like we are on a similar page. I suppose the advantages and limitations of your new design will become more apparent after it is implemented and we have made a new polymodule that can take the list of poly constraints (with JuMP expression coefficients, basis, and domain set information) from PolyJuMP.

**Comment by joehuchette** [comment]
> We could change the design of PolyJuMP a bit for that: Instead of having a default polymodule, we have a default cone approximating the cone of nonnegative polynomials.

What's the advantage of this, as opposed to a default module? I made a PR (#18) if you'd like to take a look.

**Comment by blegat** [comment]
The advantage is that we can move code to PolyJuMP that will be shared with different packages. These include [the code for 1.](https://github.com/JuliaOpt/SumOfSquares.jl/blob/c50dd9ce5c3d8c3b6d8a2951953bac4b1adde8c3/src/variable.jl#L22-L35), [the code for 2.](https://github.com/JuliaOpt/SumOfSquares.jl/blob/c50dd9ce5c3d8c3b6d8a2951953bac4b1adde8c3/src/constraint.jl#L37-L50), the code for polynomial basis for 1. and 2. and I guess more to come later.

**Comment by joehuchette** [comment]
We should probably do both. How about I move the methods you linked to PolyJuMP, and add an empty default module?

**Comment by blegat** [comment]
That would work :)
